### ISSUE TITLE
Install info is incorrect

### ISSUE THREAD

**Issue by cryptax** [dorneanu/smalisca#2]
Hi, 
This is a very minor error, but it seems that the INSTALL info is not up to date. It says:

   cd smalisca
   $ make install

but there is no Makefile is smalisca. It seems that make install must rather be done from the root of the project (above smalisca).

**Comment by dorneanu** [comment]
Yes, you're totally right. I'll update that asap. BTW: You can install smalisca using PyPI:

```
pip install smalisca
```
